// USER ACTIONS
export const SET_USER = 'SET_USER';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_MINI_USERS = 'SET_MINI_USERS';
export const SET_CURRENT_MINI_USER = 'SET_CURRENT_MINI_USER';
export const UPDATE_MINI_USER = 'UPDATE_MINI_USER';
export const DELETE_CURRENT_MINI_USER = 'DELETE_CURRENT_MINI_USER';
export const ADD_MINI_USER = 'ADD_MINI_USER';

export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';

export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';

export const ADD_ACTIVITY = 'ADD_ACTIVITY';

export const UPLOAD_FILE = 'UPLOAD_FILE';

export const ADD_NEWLIST_FOR_USER = 'ADD_NEWLIST_FOR_USER';
export const UPDATE_LIST_DATA = 'UPDATE_LIST_DATA';

export const FETCH_LISTS = 'FETCH_LISTS';
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS';
export const DELETE_LIST_BY_USER = 'DELETE_LIST_BY_USER';

export const FETCH_REWARDS = 'FETCH_REWARDS';
export const FETCH_REWARDS_SUCCESS = 'FETCH_REWARDS_SUCCESS';
export const UPDATE_REWARD_DATA = 'UPDATE_REWARD_DATA';


export const FETCH_ACTIVITIES_BY_SUBJECT = 'FETCH_ACTIVITIES_BY_SUBJECT';
export const SET_OPTIONAL_ACTIVITIES = 'SET_OPTIONAL_ACTIVITIES';
export const GET_ACTIVITY_BY_ID = 'GET_ACTIVITY_BY_ID';
export const GET_ACTIVITY_BY_SUBJECT = 'GET_ACTIVITY_BY_SUBJECT';
export const EDIT_ACTIVITY_BY_ID = 'EDIT_ACTIVITY_BY_ID';
export const CURRENT_USER_RESULTS = 'CURRENT_USER_RESULTS';
export const ADD_TOPIC = 'ADD_TOPIC';
export const CHECK_FILE = 'CHECK_FILE';
export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const UPDATE_RESULTS = 'UPDATE_RESULTS';
export const GET_USER_STATS = 'GET_USER_STATS';
